name: Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Run Pkg-config and OpenSSL
      run: sudo apt install pkg-config libssl-dev;

    - name: Install gcc-10
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test; sudo apt update; sudo apt install gcc-10 g++-10;

    - name: Set gcc-10 as the default one
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 250; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 250;

    - name: Prepare
      run: gcc --version; g++ --version; mkdir build;

    - name: cmake
      run: cd build; cmake ..

    - name: build
      run: cd build; make

